pipeline:
  model_type: "fuse-dit"
  ckpt_path: ["/data/bingda/ckpts/large-scale-800k/"]
  dtype: "bf16"
gen:
  prompts_dir: "../ELLA/dpg_bench/prompts"
  seed: 42
  H: 512
  W: 512
  scale: 6.0
  steps: 25
  negative_prompt: null
  instruction: ""